name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false
      matrix:
        python-version: [3.13]
        poetry-version: [2.3.2]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: bookstore_db
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: 1
      DJANGO_SECRET_KEY: batata
      DJANGO_ALLOWED_HOSTS: localhost
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: bookstore_db
      SQL_USER: dev
      SQL_PASSWORD: dev
      SQL_HOST: localhost
      SQL_PORT: 5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry ${{ matrix.poetry-version }}
        working-directory: ./bookstore
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}

      - name: Install dependencies
        working-directory: ./bookstore
        run: poetry install
